### ISSUE TITLE
เสนอหัวข้อ โปรเจ็ค

### ISSUE THREAD

**Issue by SCKagura** [SCKagura/Com_prog_project#1]
• หัวข้ออะไรก็ได้
• Game: Board Game, Card Game, Turn-based Game, Action Game, Puzzle Game ...
• เครื่องมือทางคณิตศาสตร์หรือวิทยาศาสตร์: Matrix, Complex number, Calculus,
Physics.
• โปรแกรมวิเคราะห์ข้อมูล: ข้อมูลเชิงตัวเลข ภาพข้อความ -> สรุป,ทำนาย,จำแนก,แสดงผล
เป็นกราฟ, ...
• ระบบเกี่ยวกับการเรียนการสอน: ฝึกภาษา, สอนโปรแกรม
• ระบบจัดการกิจการต่าง ๆ: Library, Hotel, Shopping, ....
• โปรแกรมใช้งานอื่นๆ : Chat-bot, Hardware Controlling
-ต้องใช้ภาษา C++ เท่านั้น
• Interface จะอยู่บน Console หรือเป็น GUI ก็ได ้
• สมาชิกต้องทำงานร่วมกันบน  GitHub และเปิด Repository นั้นเป็น Public
• ใช ้Library อื่นๆมาช่วยสร้างงผลงานได ้(อยากให้ลองใช)้

**Comment by 93bazmi** [comment]
ไพ่สลาฟ อยากเล่นไพ่สลาฟ 🤩🤩🤩🤩

**Comment by SCKagura** [comment]
จำคำศัพท์พอ55
