### ISSUE TITLE
โค้ดบันทึกผลคะแนนและเซฟลงไฟล์

### ISSUE THREAD

**Issue by SCKagura** [SCKagura/Com_prog_project#10]

**Comment by weerr12** [comment]
![334921884_111740801859697_8714704318372188679_n](https://user-images.githubusercontent.com/110968670/223626153-2912943d-2e2d-4b86-a1da-e826bdf00df7.png)

**Comment by weerr12** [comment]
โค้ดตัวนี้ได้ไปดูมาจากตัวอย่างในยูทูปมา
https://www.youtube.com/watch?v=eZ3oKfjnsHM
