### ISSUE TITLE
รูปความทรงจำ

### ISSUE THREAD

**Issue by SCKagura** [SCKagura/Com_prog_project#12]
เราประชุมกันเรื่องอะไร
นัดคุยกันที่ไหน
หรือรวมตัวกันที่ไหน ถ่ายรูปลงในนี้ได้เลยย

**Comment by pornchanokppp** [comment]
![image](https://user-images.githubusercontent.com/110967897/224484985-1c0b2317-59df-424b-95f7-0eac5be27eda.jpeg)

**Comment by pornchanokppp** [comment]
คอมตัวเดียวทำงานทั้งกลุ่มมีอยู่จริง![image](https://user-images.githubusercontent.com/110967897/224485020-8f4cb518-a2f2-417a-acee-635b9e3369fa.jpeg)

**Comment by SCKagura** [comment]
![image](https://user-images.githubusercontent.com/110963025/225563007-49f6f3ae-79a6-42f9-8a59-73567473eb1b.jpeg)
