### ISSUE TITLE
โค้ดคำถาม

### ISSUE THREAD

**Issue by SCKagura** [SCKagura/Com_prog_project#9]
โค้ดที่ใช้สำหรับสร้างคำถาม

**Comment by Phurinon** [comment]
![Uploading A2C23355-BAAC-41E6-AA77-B1ED04FF09E3.png…]()

**Comment by Phurinon** [comment]
![code quiz](https://user-images.githubusercontent.com/110959150/223630600-d1de58c1-6d68-4654-aacd-aeb48e92ba29.png)
